export const DMV_STATUS_KIND = 7000;

export const DMV_TRANSLATE_JOB_KIND = 5002;
export const DMV_TRANSLATE_RESULT_KIND = 6002;

export const DMV_CONTENT_DISCOVERY_JOB_KIND = 5300;
export const DMV_CONTENT_DISCOVERY_RESULT_KIND = 6300;
