name: Build exe

on:
  push:
    tags:
      - "v*" # Trigger on version tags
    branches:
      - master
  # Allows manual trigger
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Set build env
        run: |
          echo "VITE_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "VITE_APP_VERSION=$(jq -r .version ./package.json)" >> $GITHUB_ENV

      - name: Build
        run: pnpm build

      - name: Redirect 404 to Index for SPA
        run: cp dist/index.html dist/404.html

      - name: Copy app to exe/web
        run: cp -r dist/* exe/web

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Create bin directory
        run: mkdir -p exe/bin

      - name: Build exe
        run: cd exe && make

      # Upload as workflow artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: exe/bin/*
